package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    private JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;
    private TupleDesc td;
    private Tuple tup;
    private Set<String> tpSet = new HashSet<>();
    private boolean debug = false;
    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here

        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());

    }
    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child2.getTupleDesc().getFieldName(p.getField1());

    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return td;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
        tup = null;
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
        tup = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here

        close();
        open();

    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here

//        HashMap<Tuple> tpMap = new HashMap();
        while (true) {
            if (tup == null) {
                if (child1.hasNext()) {
                    tup = child1.next();
                    child2.rewind();
                } else {
                    return null;
                }
            }
            while (child2.hasNext()) {
                Tuple tup2 = child2.next();
                if (p.filter(tup, tup2)) {
//                    System.out.println("tup: " + tup.toString() + " tup2: " + tup2.toString());
                    Tuple tpMerge = Tuple.merge(tup, tup2);
                    // Check if where is an existing tuple in the result
                    if (tpSet.contains(tpMerge.toString())){
                        continue;
                    }
                    tpSet.add(tpMerge.toString());

                    if (debug){
                        System.out.println("tup: " + tup.toString() + " tup2: " + tup2.toString());
                        System.out.println("tuple merge: " + tpMerge.toString());
                        System.out.println("tuple merge: " + tpMerge.toString());
                    }

                    return tpMerge;
                }
            }
            tup = null;
        }
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{child1, child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        assert children.length == 2;
        child1 = children[0];
        child2 = children[1];
    }

}
